version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: database
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env
    ports:
      - "7070:7070"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_CONNECTION=jdbc:postgresql://postgres:5432/db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: